; ********** History **********
; Creator：Weber
; Modified Date：2025/09/01
; Note：
;
;*****************************
;[Section]
; ********** 請依照規範填寫，程式會依規範進行環境設定 **********
;===========================================================================================================
[General]
Project = Cabin                       ;Front or Cabin
Test Mode = EMC	      	      ;EOL, EMC/DQA, PrePV, EMC
Target Folder =                       ;Upload 54 Server Target Folder Path
TB_Version  = C-TestBoard-FACTORY-5.4.3 ;Test Board SW Version
ZCU_Version = V3.1.8                ;ZCU SW Version
Total Set = 1                        ;Box UI Set Number
PowerSupplyControl = Disable          ;Enable/Disable
DQA_INI_Path = C:\Users\Sam_Chu\Documents\ESPEC-EX-3rd.ini ;
;===========================================================================================================
[MES]
MESUpLoad = N
Site = CN10
Line = PCBC
Customer = SMT
;===========================================================================================================
[DoIP]
; for ZCU
Bind_IP = 192.168.5.100
Max_Conn = 4
UDP_Port = 13400
TCP_Port = 13400
Source_Address = 0x0e00
Target_Address = 0x0e01
;===========================================================================================================
[MQTT]
; For TB
IP_Address = 192.168.1.100

;===========================================================================================================
[Box_01]
CR1001_IP   = 192.168.1.100
Group       = FCT
Fixture_No  = CAX5020Q18LAE721-01
TB_SN       = 123456789
Nano_IP     = 192.168.5.1
PS_IP       = 192.168.1.101
PS_Port     = 2268 
PBox_Fr_IP  = 192.168.1.51
Cs_50W_IP   = 192.168.1.51 
Cs_100W_IP  = 192.168.1.52
Cs_200W_IP  = 192.168.1.53

[Box_02]
CR1001_IP   = 192.168.1.200
Group       = FCT
Fixture_No  = CAX5020Q18LAE721-02
TB_SN       = 123456789
Nano_IP     = 192.168.1.42
PS_IP       = 192.168.1.101
PS_Port     = 2268 
PBox_Fr_IP  = 192.168.1.51
Cs_50W_IP   = 192.168.1.51 
Cs_100W_IP  = 192.168.1.52
Cs_200W_IP  = 192.168.1.53

[Box_03]
CR1001_IP   = 192.168.1.200
Group       = FCT
Fixture_No  = CAX5020Q18LAE721-03
TB_SN       = 123456789
Nano_IP     = 192.168.1.43
PS_IP       = 192.168.1.101
PS_Port     = 2268 
PBox_Fr_IP  = 192.168.1.51
Cs_50W_IP   = 192.168.1.51 
Cs_100W_IP  = 192.168.1.52
Cs_200W_IP  = 192.168.1.53

[Box_04]
CR1001_IP   = 192.168.1.200
Group       = FCT
Fixture_No  = CAX5020Q18LAE721-04
TB_SN       = 123456789
Nano_IP     = 192.168.1.44
PS_IP       = 192.168.1.101
PS_Port     = 2268 
PBox_Fr_IP  = 192.168.1.51
Cs_50W_IP   = 192.168.1.51 
Cs_100W_IP  = 192.168.1.52
Cs_200W_IP  = 192.168.1.53
