cookie:
  expiry_days: 7
  key: change-this-to-a-random-secret-key-32chars
  name: atp_log_analyzer
credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      last_login: '2026-04-15 22:03:24'
      logged_in: false
      name: Administrator
      password: $2b$12$MiGNHLJZYnb3jxgC8OICseNUPM6k6s1ahdAqNADYDweuEUoSRcBge
      role: admin
    sam:
      email: ''
      name: sam
      password: $2b$12$Xt5XzyricicShk5CRoHQ.ekCS9u9OzZAk5NwqRYJBf5.ml2yHQfXm
      role: user
    user:
      email: user@example.com
      failed_login_attempts: 0
      logged_in: false
      name: user
      password: $2b$12$sOWeh6yyr.nQGJNlPpBx0.7VwmTXnJYeeOygd34cNFgt4PMMJxMhW
      role: user
