cookie:
  expiry_days: 7
  key: change-this-to-a-random-secret-key-32chars
  name: atp_log_analyzer
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrator
      password: $2b$12$MiGNHLJZYnb3jxgC8OICseNUPM6k6s1ahdAqNADYDweuEUoSRcBge
      role: admin
    user:
      email: user@example.com
      name: user
      password: $2b$12$sOWeh6yyr.nQGJNlPpBx0.7VwmTXnJYeeOygd34cNFgt4PMMJxMhW
      role: user
