[theme]
base = "dark"
primaryColor = "#00AAFF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1C2333"
textColor = "#FAFAFA"
font = "monospace"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
