[theme]
base = "light"
primaryColor = "#00AAFF"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
